package nuzzgraph.dbclient.gui;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.annotation.PostConstruct;
import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;

/**
 * User: Mark Nuzzolilo
 * Date: 3/28/12
 * Time: 12:09 PM
 */
public class TabNodeRaw_gui extends JComponent
{
    JPanel panelMain;
    JSplitPane split1;
    JPanel panelHeader;
    JPanel panelNodeRawPropertiesData;
    JPanel panelListRaw;
    JList<String> listRawNodes;
    JScrollBar scrollbarNodeSelectionRaw;
    JPanel panelPropertyHeader;
    JScrollPane spListRaw;
    JSplitPane split2;
    JPanel panelNodeRaw;
    JSplitPane split3;
    JPanel panelNodeRawPropertiesOuter;
    JPanel panelNodeRawPropertiesInner;
    JScrollPane spNodeRawProperties;
    JButton bAddProperty;
    JScrollBar scrollBarNodeRawProperties;
    JPanel panelNodeRelationships;
    JSplitPane split4;
    JButton bNewNode;
    JButton bSaveNode;
    JButton bReloadNode;
    JButton bDeleteNode;
    JLabel lblNodeId;
    JPanel panelNodeRawPropertiesDataOuter;

    TabNodeRaw logic;

    public TabNodeRaw_gui()
    {
    }

    @PostConstruct
    public void init()
    {
        logic = new TabNodeRaw(this);
    }


    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        panelMain = new JPanel();
        panelMain.setLayout(new FormLayout("fill:d:grow", "fill:d:grow"));
        split1 = new JSplitPane();
        split1.setContinuousLayout(true);
        split1.setDividerLocation(160);
        split1.setDividerSize(0);
        split1.setOneTouchExpandable(false);
        split1.setOrientation(1);
        split1.setResizeWeight(0.0);
        CellConstraints cc = new CellConstraints();
        panelMain.add(split1, cc.xy(1, 1, CellConstraints.DEFAULT, CellConstraints.FILL));
        spListRaw = new JScrollPane();
        split1.setLeftComponent(spListRaw);
        spListRaw.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        panelListRaw = new JPanel();
        panelListRaw.setLayout(new FormLayout("fill:max(d;150px):grow,fill:d:noGrow", "fill:d:grow"));
        spListRaw.setViewportView(panelListRaw);
        panelListRaw.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        scrollbarNodeSelectionRaw = new JScrollBar();
        panelListRaw.add(scrollbarNodeSelectionRaw, cc.xy(2, 1, CellConstraints.RIGHT, CellConstraints.FILL));
        listRawNodes = new JList();
        panelListRaw.add(listRawNodes, cc.xy(1, 1, CellConstraints.DEFAULT, CellConstraints.FILL));
        split2 = new JSplitPane();
        split2.setDividerLocation(51);
        split2.setDividerSize(0);
        split2.setOrientation(0);
        split1.setRightComponent(split2);
        split2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        panelNodeRaw = new JPanel();
        panelNodeRaw.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        split2.setRightComponent(panelNodeRaw);
        panelNodeRaw.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        split3 = new JSplitPane();
        split3.setDividerLocation(380);
        split3.setDividerSize(0);
        split3.setOrientation(1);
        split3.setResizeWeight(0.5);
        panelNodeRaw.add(split3, cc.xy(1, 1, CellConstraints.DEFAULT, CellConstraints.FILL));
        split3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        panelNodeRawPropertiesOuter = new JPanel();
        panelNodeRawPropertiesOuter.setLayout(new FormLayout("center:max(d;300px):grow,fill:d:noGrow", "center:d:grow"));
        split3.setLeftComponent(panelNodeRawPropertiesOuter);
        panelNodeRawPropertiesOuter.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0), null));
        split4 = new JSplitPane();
        split4.setDividerSize(0);
        split4.setOrientation(0);
        panelNodeRawPropertiesOuter.add(split4, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
        split4.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(0, 0, 0, 0), null));
        panelNodeRawPropertiesInner = new JPanel();
        panelNodeRawPropertiesInner.setLayout(new BorderLayout(0, 0));
        split4.setLeftComponent(panelNodeRawPropertiesInner);
        panelNodeRawPropertiesInner.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        panelPropertyHeader = new JPanel();
        panelPropertyHeader.setLayout(new FormLayout("right:d:grow,fill:d:noGrow", "fill:35px:grow"));
        panelNodeRawPropertiesInner.add(panelPropertyHeader, BorderLayout.CENTER);
        panelPropertyHeader.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, new Font(panelPropertyHeader.getFont().getName(), panelPropertyHeader.getFont().getStyle(), panelPropertyHeader.getFont().getSize())));
        final JLabel label1 = new JLabel();
        label1.setText("Node Properties");
        panelPropertyHeader.add(label1, cc.xy(1, 1, CellConstraints.CENTER, CellConstraints.DEFAULT));
        bAddProperty = new JButton();
        bAddProperty.setText("Add Property");
        panelPropertyHeader.add(bAddProperty, cc.xy(2, 1, CellConstraints.RIGHT, CellConstraints.CENTER));
        spNodeRawProperties = new JScrollPane();
        split4.setRightComponent(spNodeRawProperties);
        spNodeRawProperties.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        panelNodeRawPropertiesDataOuter = new JPanel();
        panelNodeRawPropertiesDataOuter.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow"));
        spNodeRawProperties.setViewportView(panelNodeRawPropertiesDataOuter);
        panelNodeRawPropertiesData = new JPanel();
        panelNodeRawPropertiesData.setLayout(new GridBagLayout());
        panelNodeRawPropertiesDataOuter.add(panelNodeRawPropertiesData, cc.xy(1, 1, CellConstraints.DEFAULT, CellConstraints.TOP));
        panelNodeRawPropertiesData.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        scrollBarNodeRawProperties = new JScrollBar();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.fill = GridBagConstraints.VERTICAL;
        panelNodeRawPropertiesData.add(scrollBarNodeRawProperties, gbc);
        panelNodeRelationships = new JPanel();
        panelNodeRelationships.setLayout(new FormLayout("fill:d:grow", "center:d:grow"));
        split3.setRightComponent(panelNodeRelationships);
        panelHeader = new JPanel();
        panelHeader.setLayout(new FormLayout("fill:d:noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:max(d;4px):noGrow", "center:d:grow"));
        split2.setLeftComponent(panelHeader);
        panelHeader.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(), null));
        bNewNode = new JButton();
        bNewNode.setText("New Node");
        panelHeader.add(bNewNode, cc.xy(1, 1));
        bSaveNode = new JButton();
        bSaveNode.setText("Save Node");
        panelHeader.add(bSaveNode, cc.xy(3, 1));
        bReloadNode = new JButton();
        bReloadNode.setText("Reload Node");
        panelHeader.add(bReloadNode, cc.xy(5, 1));
        bDeleteNode = new JButton();
        bDeleteNode.setText("Delete Node");
        panelHeader.add(bDeleteNode, cc.xy(7, 1));
        lblNodeId = new JLabel();
        lblNodeId.setText("No node loaded");
        panelHeader.add(lblNodeId, cc.xy(9, 1));
        spListRaw.setVerticalScrollBar(scrollbarNodeSelectionRaw);
        label1.setLabelFor(spListRaw);
        spNodeRawProperties.setVerticalScrollBar(scrollBarNodeRawProperties);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    { return panelMain; }
}
